version: '3.8'
services:
web:
build: ./backend
command: uvicorn app:app --host 0.0.0.0 --port 8000
environment:
- OPENAI_API_KEY
- OPENAI_MODEL=gpt-4.1
ports:
- '8000:8000'
volumes:
- ./backend:/app
frontend:
build: ./frontend
ports:
- '3000:3000'
volumes:
- ./frontend:/app
